version: '3'
services:
  coredns:
    ports:
      - "53:53/udp"
    image: coredns/coredns:latest
    restart: always
    volumes:
    - ./:/root/
    command:
    - -conf
    - /root/Corefile
  etcd:
    image: quay.io/coreos/etcd
    ports:
    - "2379:2379"
    - "2380:2380"
    volumes:
    - ./data:/etcd-data
    command:
    - /usr/local/bin/etcd
    - --data-dir=/etcd-data
    - --name=node1
    - --listen-peer-urls=http://0.0.0.0:2380
    - --advertise-client-urls=http://0.0.0.0:2379
    - --listen-client-urls=http://0.0.0.0:2379
